[tool.poetry]
name = "primal-digest"
version = "0.1.0"
description = ""
authors = ["ChrisKent <chrisgkent@gmail.com>"]
readme = "README.md"
packages = [{include = "primal_digest"}]

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.24"
primer3-py = "^0.6.1"
parasail = "^1.3.3"
biopython = "^1.80"
diskcache = "^5.4.0"
kmer-tools = {path = "/Users/kentcg/rust_testing/kmertools/target/wheels/kmer_tools-0.1.0-cp39-cp39-macosx_11_0_arm64.whl"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
primal-digest = 'primal_digest.main:main'