[tool.poetry]
name = "primal-digest"
version = "0.1.0"
description = ""
authors = ["ChrisKent <chrisgkent@gmail.com>"]
readme = "README.md"
packages = [{include = "primal_digest"}]

[tool.poetry.dependencies]
python = "^3.11"
primer3-py = "^0.6.1"
parasail = "^1.3.3"
biopython = "^1.80"
diskcache = "^5.4.0"
kmer-tools = "^0.1.0"
Jinja2 = "^3.1.2"
numpy = "^1.24.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
primal-digest = 'primal_digest.main:main'