[tool.poetry]
name = "primal-digest"
version = "1.1.2"
description = ""
authors = ["ChrisKent <chrisgkent@gmail.com>"]
readme = "README.md"
packages = [{include = "primal_digest"}]

[tool.poetry.dependencies]
python = "^3.11"
primer3-py = "^1.2.2"
biopython = "^1.80"
Jinja2 = "^3.1.2"
numpy = "^1.24.2"
primaldimer_py = "1.0.1"
networkx = "^3.1"
loguru = "^0.7.0"
kaleido = "0.2.1"
plotly = "^5.16.1"
tqdm = "^4.66.1"
pytest = "^7.4.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
primal-digest = 'primal_digest.main:main'